### ISSUE TITLE
Failure to Load StippleUI Assets Consistently

### ISSUE THREAD

**Issue by TheCedarPrince** [AbhimanyuAryan/MultiRoute#6]
Hi @AbhimanyuAryan,

I am opening this issue as there is inconsistent behavior with loading StippleUI assets with this example.
For example, when starting the webapp, the assets are not loaded in:

![image](https://user-images.githubusercontent.com/29561456/154305204-11273c77-4f90-4e63-8ece-9227de3a03e3.png)

Then, if I were to go to `DataexplorerController.jl` and change `init(Model)` to `init(Model())` and reload the webapp, it works properly:

![image](https://user-images.githubusercontent.com/29561456/154306171-53c5c440-d79a-4f64-b4d2-618ce9905f96.png)

@essenciary, I cannot tell if this is an inconsistency with Stipple as a whole or is just limited to this example.
CC'ing you here to see this issue. 

What could be the most likely issue here?
Thanks!

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince ﻿﻿

```Then, if I were to go to DataexplorerController.jl and change init(Model) to init(Model()) and reload the webapp, it works properly:```

No I see same error. You need to check again

**Comment by essenciary** [comment]
Changing between `init(Model)` and `init(Model())` should make no difference. `init(Model())` calls `init(typeof(Model()))`

**Comment by essenciary** [comment]
@TheCedarPrince Can you please provide: 

1/ output of `pkg> st` - if you're not on the latest versions of all packages, please upgrade to latest
2/ check the browser console (developer tools) and see if there are any JS errors
3/ check the Julia REPL and see if there are any errors upon app startup

If there is nothing relevant, it would be great to share the app so we can run it and take a look.

**Comment by TheCedarPrince** [comment]
Hey @essenciary , 

Here is a link to my current branch where these errors are happening: https://github.com/AbhimanyuAryan/MultiRoute/pull/5

And here is the information you requested: 

1. All of my packages are still up to date, but here are the packages:

```
(MultiRoute) pkg> st
     Project MultiRoute v0.1.0
      Status `/home/src/Projects/open_source_contribs/MultiRoute/Project.toml`
  [a93c6f00] DataFrames v1.3.2
  [c43c736e] Genie v4.13.0
  [6d011eab] Inflector v1.0.1
  [e6f89c97] LoggingExtras v0.4.7
  [739be429] MbedTLS v1.0.3
  [ce6b1742] RDatasets v0.7.7
  [340e8cb6] SearchLight v2.2.0
  [4acbeb90] Stipple v0.20.5
  [ec984513] StipplePlotly v0.10.0
  [a3c5d34a] StippleUI v0.15.2
  [ade2ca70] Dates
  [56ddb016] Logging
```

2. There do appear to be errors:

![image](https://user-images.githubusercontent.com/29561456/154512252-3c044c8b-a401-4406-ba0a-47a277bf695c.png)


3. This is what I see within my REPL and yes, there are errors when I try to access the route `dataexplorer` - I just do not know what they mean:

```
 _____         _
|   __|___ ___|_|___
|  |  | -_|   | | -_|
|_____|___|_|_|_|___|

| Web: https://genieframework.com
| GitHub: https://github.com/genieframework/Genie.jl
| Docs: https://www.genieframework.com/docs/tutorials/Overview.html
| Discord: https://discord.com/invite/9zyZbD6J7H
| Twitter: https://twitter.com/GenieMVC

Active env: DEV

┌ Warning:
│             No secret token is defined through `Genie.secret_token!("token")`. Such a token
│             is needed to hash and to encrypt/decrypt sensitive data in Genie, including cookie
│             and session data.
│
│             If your app relies on cookies or sessions make sure you generate a valid token,
│             otherwise the encrypted data will become unreadable between app restarts.
│
│             You can resolve this issue by generating a valid `config/secrets.jl` file with a
│             random token, calling `Genie.Generator.write_secrets_file()`.
│
└ @ Genie ~/.julia/packages/Genie/JHrq4/src/genie_module.jl:222

Ready!

julia> up()
┌ Info: 2022-02-17 10:05:10
└ Web Server starting at http://127.0.0.1:8000
Genie.AppServer.ServersCollection(Task (runnable) @0x00007faf961b9150, nothing)

julia> [ Info: 2022-02-17 10:05:29 GET /dataexplorer 200
[ Info: 2022-02-17 10:05:29 GET /stipple.jl/master/assets/css/stipplecore.css 200
[ Info: 2022-02-17 10:05:29 GET /stippleui.jl/master/assets/css/quasar.min.css 200
[ Info: 2022-02-17 10:05:29 GET /genie.jl/master/assets/js/dxsvnrhtzlykrxjrbveejtxplixrjiwf/channels.js 200
┌ Error: 2022-02-17 10:05:29 GET /stipple.jl/master/assets/js/underscore-min.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:29 GET /stipple.jl/master/assets/js/vue.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:29 GET /stipple.jl/master/assets/js/stipplecore.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:29 GET /stipple.jl/master/assets/js/watchers.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
[ Info: 2022-02-17 10:05:29 GET /stippleui.jl/master/assets/js/quasar.umd.min.js 200
[ Info: 2022-02-17 10:05:29 GET /stippleplotly.jl/master/assets/js/plotly2.min.js 200
[ Info: 2022-02-17 10:05:29 GET /stippleplotly.jl/master/assets/js/resizesensor.min.js 200
[ Info: 2022-02-17 10:05:29 GET /stippleplotly.jl/master/assets/js/lodash.min.js 200
[ Info: 2022-02-17 10:05:30 GET /stippleplotly.jl/master/assets/js/vueresize.min.js 200
[ Info: 2022-02-17 10:05:30 GET /stippleplotly.jl/master/assets/js/vueplotly.min.js 200
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/underscore-min.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/vue_filters.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/keepalive.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/vue.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/stipplecore.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/vue_filters.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/watchers.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
┌ Error: 2022-02-17 10:05:30 GET /stipple.jl/master/assets/js/keepalive.js 404
└ @ Genie.Router ~/.julia/packages/Genie/JHrq4/src/Router.jl:163
```

**Comment by essenciary** [comment]
@TheCedarPrince Well this is interesting, but basically your use of the global model instance seems to affect the initialisation of the model. Which is an unexpected but good side-effect... Global models are now considered bad practice due to shared sate, very poor performance, etc. 

All you need to do is to remove the `my_model = init(IrisModel)` line and initialize the model within the route handler (so you have one model instance per request): 

```julia
function explorer()
    html(:dataexplorer, "explorer.jl", model = init(IrisModel), context = @__MODULE__)
end
```

---

If you need to maintain the state of the model between page reloads use the new `ModelStorage` API, like this: 

```julia
using Stipple.ModelStorage.Sessions
Stipple.ModelStorage.Sessions.init()
```

Then instead of `init(IrisModel)` use `init_from_storage(IrisModel)`

---

While at this, the current structure of the code doesn't help a lot. The idea of using views is to structure the code based on responsibilities. Meaning that you should move the `page(...)` code inside the `views/explorer.jl` file and delete the `ui(...)` function.

---

Finally, you don't need to declare `using Genie` and `using Genie.Renderers.Html` as these are automatically imported by `Stipple`. 

--- 

Should look like this: 

<img width="711" alt="image" src="https://user-images.githubusercontent.com/11292378/154551149-8e160a59-6cd6-4994-a79b-3a800edd46c4.png">

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/11292378/154553924-12e29313-0f31-4eb1-b775-85746cbcc43e.png">

**Comment by TheCedarPrince** [comment]
Hey @essenciary , 

 I feel like I owe you an apology about how bad my code was to read!
Thank you for dealing the sloppiness of it!

I just made all the changes you suggested and it works perfectly for `Dataexplorer.jl`.
However, I am still having the problems with the other view called `Plotsdataexplorer.jl`.
here I do not know how to have reactivity while also using the MVC model.
Could you or @AbhimanyuAryan  help me here?
Thank you!

**Comment by AbhimanyuAryan** [comment]
@TheCedarPrince I will look into it. No problem.

**Comment by AbhimanyuAryan** [comment]
closing this since it's resolved
